
CREATE TABLE  "PESANAN" 
   (	"PESANAN_ID" NUMBER  CONSTRAINT "PESANAN_ID_PP" NOT NULL ENABLE,
   "PESANAN_TANGGAL" DATE CONSTRAINT "PES_PESANAN_TANGGAL_PP" NOT NULL ENABLE, 
	"PESANAN_MODE" VARCHAR2(25), 
	 CONSTRAINT "DAE_ID_PK" PRIMARY KEY ("DAERAH_ID")
  USING INDEX  ENABLE
   )
